spring.application.name=septicpath
gg.jte.development-mode=true

app.data.root=./data/raw
app.storage.root=./storage
app.site.base-url=${APP_SITE_BASE_URL:https://septicpath.com}
server.forward-headers-strategy=framework
