spring.application.name=septicpath
gg.jte.development-mode=${GG_JTE_DEVELOPMENT_MODE:true}
gg.jte.use-precompiled-templates=${GG_JTE_USE_PRECOMPILED_TEMPLATES:false}

app.data.root=./data/raw
app.storage.root=./storage
app.site.base-url=${APP_SITE_BASE_URL:https://septicpath.com}
server.forward-headers-strategy=framework
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,application/json,image/svg+xml
server.compression.min-response-size=1024
spring.web.resources.cache.cachecontrol.max-age=365d
