package com.example.septic.web;

import java.util.List;

/** Public editorial case facts only. Never loads the private operations ledger. */
public final class StudioCaseStudies {
    private StudioCaseStudies() {}
    public record Fact(String source, String value) {}
    public record Study(String slug, String place, String title, String hero, String mobile, String question, String intro, String heading, List<Fact> facts, List<String> story, String limit, String image, String caption, String original) {
        public String angle() {
            return switch (slug) {
                case "roane" -> "Search beyond the listing.";
                case "anderson" -> "Read the stage. Then the number.";
                case "st-croix" -> "Find the relevant pages. Keep their differences.";
                case "overton" -> "Follow older clues. Test the match.";
                case "williamson" -> "Ask what happened after the permit.";
                case "morgan" -> "The map identified the property. Not the system.";
                case "haverhill" -> "Test the recent claim against the city file.";
                case "cole" -> "Confirm the search. Do not invent the location.";
                default -> throw new IllegalStateException("Missing case direction: " + slug);
            };
        }
        public String stepTitle(int index) {
            return switch (slug) {
                case "roane" -> index == 0 ? "Change the search route." : "Read the sketch with the permit.";
                case "anderson" -> index == 0 ? "Separate the document stages." : "Preserve both recorded lengths.";
                case "st-croix" -> index == 0 ? "Filter the archive." : "Do not flatten conflicting entries.";
                case "overton" -> index == 0 ? "Search historical identifiers." : "Stop short of a confirmed match.";
                case "williamson" -> index == 0 ? "Check the complete holding." : "Connect design and completion.";
                case "morgan" -> index == 0 ? "Know what the map can answer." : "Compare the returned pages.";
                case "haverhill" -> index == 0 ? "Go to the record custodian." : "Distinguish old work from recent claims.";
                case "cole" -> index == 0 ? "Request the property file." : "Confirm with the health department.";
                default -> throw new IllegalStateException("Missing case steps: " + slug);
            };
        }
        public String interludeImage() {
            return switch (slug) {
                case "roane", "overton", "cole" -> "oak-pasture-v1.webp";
                default -> "research-room-v1.webp";
            };
        }
        public String bridge() {
            return switch (slug) {
                case "overton" -> "A promising file is not yet a property match.";
                case "cole" -> "An honest search result is still an answer.";
                case "haverhill" -> "A record of repair is not proof of recent replacement.";
                default -> "The source matters. So does how you read it.";
            };
        }
    }
    public static final List<Study> ALL = List.of(
        new Study("roane", "Roane County, Tennessee", "A layout the listing could not show.", "county-property-v1.webp", "guides-mobile-v1.webp", "Where were the tank and drain field drawn?", "The property listing did not supply the system layout. A focused TDEC request recovered a historical permit and sketch.", "Three lines. One documented starting point.", List.of(new Fact("Sketch · line 01", "60 ft"), new Fact("Sketch · line 02", "80 ft"), new Fact("Sketch · line 03", "85 ft"), new Fact("Combined written lengths", "225 linear ft"), new Fact("Accompanying permit", "3 bedrooms · 900-gallon tank")), List.of("We assembled the property identifiers and requested the permit, layout, final approval and repair records. An empty public search was a search limit, not proof that no file existed.", "The returned sketch placed a tank beside the house and showed three dashed field runs. The written lengths came from the sketch; the tank capacity and design bedrooms came from the permit text.", "The unmodified agency file and a two-page explanation were delivered. The result was a documented historical layout, not a completed site inspection."), "The sketch has no north arrow and is not a scaled survey. Exact present-day location, later changes and current condition remain unverified. A construction permit alone does not establish completed installation.", "/images/case-study/tn-historical-sketch-anonymized.png", "Actual historical agency sketch · identifying header and road label omitted. Permit specifications are on a different page.", "/septic-as-built-records/#layout-case"),
        new Study("anderson", "Anderson County, South Carolina", "Two records. Two different lengths.", "work-archive-v2.webp", "work-archive-mobile-v3.webp", "The permit says 300 feet. What does the final record show?", "The state file contained both a construction permit and a later final approval. Comparing their stages mattered as much as reading their figures.", "Planned is not the same as recorded installed.", List.of(new Fact("Construction permit · planned trench", "300 ft"), new Fact("Final record · 40 + 80 + 80 ft", "200 ft"), new Fact("Recorded tank capacity", "1,000 gallons"), new Fact("Recorded design flow", "360 gallons/day"), new Fact("Approved bedroom count", "Not directly stated")), List.of("We reviewed the permit, layout and recorded capacity together after matching the property identifiers. The file supplied two different document stages.", "The construction permit planned 300 feet of trench. The final installation record listed 40, 80 and 80 feet, totaling 200. We preserved both values with their sources rather than averaging them.", "The customer received the official record and an explanatory guide. The 1,000-gallon tank and 360-gallon-per-day flow were not converted into an invented bedroom approval."), "Final approval described the historical installation, not its present condition. The drawing was not to scale and GPS fields were blank, so precise underground location remained outside the record's answer.", "", "SepticPath transcription of the published case findings, not a source scan or a physical layout. Each figure retains its document stage.", "/septic-permit-process/#design-final-case"),
        new Study("st-croix", "St. Croix County, Wisconsin", "A clearer file before an addition.", "research-room-v1.webp", "mobile-research-v1.webp", "Can the old archive explain the system before an addition?", "A 26-page archive needed more than a summary number. The useful result separated revised records from older layouts and an unrelated appendix.", "26 pages reviewed. Three relevant pages selected.", List.of(new Fact("Inspection · tank capacity", "1,200 gallons"), new Fact("Revised plan · tank capacity", "1,255 gallons"), new Fact("Application · tank capacity", "1,200 gallons"), new Fact("Recorded design", "4 bedrooms · 600 gallons/day"), new Fact("Recorded dispersal", "45 chambers · 3 cells")), List.of("We linked the statewide parcel result to the County's property-file archive, then reviewed its 26-page packet. Revised system pages were separated from superseded layouts and an unrelated appendix.", "The inspection and application recorded 1,200 gallons, while the revised plan showed 1,255. Both entries were preserved instead of silently choosing a single capacity.", "The customer received a focused three-page extract and explanation. It made the relevant record stages easier to review without treating the archive as permission for a new addition."), "Relative layout clues are not precise field coordinates. A rectangular tank symbol does not establish outside tank dimensions. Current condition and approval for a proposed addition require separate review.", "", "SepticPath comparison of the published case findings. These are distinct source entries, not a newly verified single tank capacity. No other property's drawing is substituted.", "/septic-tank-location-records/#addition-file-case"),
        new Study("overton", "Overton County, Tennessee", "A file found. A match still open.", "oak-pasture-v1.webp", "guides-mobile-v1.webp", "Can earlier owner and road names uncover an older file?", "Historical clues led to a 1993 repair file. The missing modern street number meant the possible connection could not become a confirmed property match.", "Useful clues. An explicit limit.", List.of(new Fact("Candidate record", "1993 repair file"), new Fact("Supporting identity clues", "Former owner + road wording"), new Fact("Missing identity anchor", "Modern street number"), new Fact("Property match", "Unconfirmed")), List.of("Public sources did not supply a directly accessible permit or layout. Earlier owner and road-name clues were included in the TDEC archive request.", "The returned repair file supported a possible connection, but did not print the modern street number. That limitation was disclosed with the delivered record.", "Finding the file was progress, not proof of identity. Its system specifications were not presented as confirmed facts about the current property."), "The candidate file remains a limited match. Its drawing and system specifications must not be relied on as the current property's confirmed layout or condition. A correct email subject cannot supply a missing identifier on an attachment.", "/images/case-study/redacted/overton-system-layout-public.png", "Actual excerpt from the candidate repair file · identifying details omitted · property match remains unconfirmed.", "/septic-permit-search-by-address/#old-address-case"),
        new Study("williamson", "Williamson County, Tennessee", "The permit. Then the completion record.", "research-room-v1.webp", "work-archive-mobile-v3.webp", "Can the file show both the approved design and its completion?", "The county returned a 1994 construction permit and Certificate of Completion. Read together, they answered more than either document could alone.", "Two stages. One documented history.", List.of(new Fact("Construction permit", "1994 · three-bedroom design"), new Fact("Septic tank recorded", "1,000 gallons"), new Fact("Pump tank recorded separately", "1,000 gallons"), new Fact("Trench specification", "370 linear ft · four trenches"), new Fact("Certificate of Completion", "Construction approval recorded")), List.of("The county identified the construction permit and Certificate of Completion as its complete holding for this request. The pages were checked against the property's identifiers and consistent site geometry.", "The permit described a new alternating system, with a septic tank, separate pump tank and four trenches. The completion certificate added construction approval and a relative layout sketch.", "The customer received both unaltered county documents and a two-page Record Brief. The explanation kept the original design, completion stage and field-location limits distinct."), "Historical completion approval does not verify today's working condition, later changes or exact underground positions. The relative sketch is a documentary starting point; a current field locate is still needed before ground work.", "", "Anonymized case summary based on the reviewed county documents and recorded delivery. Original scans are not displayed here; this comparison is not an agency document.", ""),
        new Study("morgan", "Morgan County, Alabama", "Before the pool, understand the file.", "morgan-garden-v1.webp", "morgan-garden-v1.webp", "Where are the tank and field lines before a pool is planned?", "An Approval for Use and installer certification supplied a schematic starting point. Their line-length entries also needed to be read carefully.", "A useful layout. A difference worth keeping.", List.of(new Fact("Page 1 · three 70-foot runs", "210 ft"), new Fact("Page 2 · installer total", "Appears to read 200 ft"), new Fact("Recorded tank capacity", "1,000 gallons"), new Fact("Separate washer line", "50 ft"), new Fact("Current field location", "Still needs physical confirmation")), List.of("Parcel details supplied identity clues, but the public GIS layers reviewed had no septic layer. Aerial imagery could not reliably locate the tank or field. We moved to the health department's installation records.", "After verifying the two-page file's property match, we compared the sketch with the installer certification. Their totals differed. We kept both readings with their sources; we did not average them or silently correct the handwriting.", "The original record was delivered with a concise interpretation of the tank, relative field layout and separate washer line. The next step remained a licensed physical locate before final pool placement."), "The old schematic does not establish that its offsets remain accurate after landscaping, repairs or undocumented changes. The 210-foot and apparent 200-foot entries are not a new field measurement, and the record review does not approve a pool location.", "", "Anonymized comparison of the reviewed two-page record. The second-page handwriting is preserved as an apparent reading, not silently treated as certain. Original scans are not displayed here.", ""),
        new Study("haverhill", "Haverhill, Massachusetts", "A recent claim. An older record.", "work-archive-v2.webp", "work-archive-mobile-v3.webp", "Does the city file document the reported recent field replacement?", "The request concerned a leach-field replacement said to have happened in recent years. The city's answer identified an older repair permit, not a recent replacement file.", "What was found is not what was claimed.", List.of(new Fact("Question under review", "Recent leach-field replacement"), new Fact("Record returned", "1988 repair permit"), new Fact("City's file response", "Only record on file"), new Fact("Recent replacement documentation", "Not supplied"), new Fact("Outcome", "Bounded findings delivered")), List.of("We cross-checked GIS identifiers, the public permit portal, indexed records and listing information. None supplied the claimed replacement file. That gap shaped a focused request to the city's Health Department.", "The city completed the search and identified a 1988 Disposal Works repair permit as the only record on file. Associated historical plans were available for office review; no electronic plan or recent replacement record was supplied.", "The customer received the verified conclusion, an agency-response excerpt and a readable permit copy. The conclusion was that the city file did not document the reported recent replacement, not that the work could never have happened."), "An older repair permit does not substantiate a recent replacement, final completion or current system condition. The scope is the city's recorded response; contractor records, private documents and field findings may answer different questions.", "", "Anonymized summary of the city response and reviewed historical permit. No claim is made that a missing city record proves no work occurred. Original correspondence and scans are not displayed here.", ""),
        new Study("cole", "Cole County, Missouri", "No file found. A clear answer anyway.", "oak-pasture-v1.webp", "guides-mobile-v1.webp", "Can county records identify an existing tank's location?", "The search reached the responsible department, but did not recover a usable layout. The customer received that limitation and a practical next step without a package charge.", "A confirmed search limit, not an invented location.", List.of(new Fact("County Clerk", "Written no-record response"), new Fact("County Health Department", "Separately confirmed no file"), new Fact("Usable tank location or layout", "Not recovered"), new Fact("Optional package charge", "None"), new Fact("Next step", "Private records or a professional locate")), List.of("We matched the address to the official parcel and checked assessor, jurisdiction and public map sources. No property-level septic drawing viewer was exposed. We used the verified County records route to request the complete file.", "The County Clerk returned a written no-record result. The Health Department separately confirmed receiving the request and having no files associated with the requested property.", "The customer received the bounded conclusion and the physical-locate next step. No $29 package charge was made because a usable tank location or layout had not been recovered."), "A county no-file response does not prove that a tank is absent. It also does not exclude a drawing held by a former owner, installer, service company or closing file. The underground location and condition remain unverified.", "", "Anonymized account of the recorded county responses and customer closeout. This is a search-outcome summary, not a property diagram or a general claim about all county records.", "")
    );
}
